package com.bfg.watchfaces.generator

import kotlin.math.cos
import kotlin.math.sin

/**
 * A glyph as an Android `VectorDrawable`, so the WATCH can draw one too.
 *
 * ## Why this exists
 *
 * [ComplicationGlyphs] is the single description and each platform executes it:
 * AWT in `:workbench`, Canvas in `:mobile`, WFF in [GlyphWff]. `:wear` had no
 * executor at all, because until now nothing on the watch drew a glyph -- the
 * dial gets its icons from the complication PROVIDER, and the providers were
 * all Google's.
 *
 * This app's own provider has to supply its own icon, and a complication's
 * `MonochromaticImage` wants a drawable resource rather than a shape list. So
 * this converts, and the result is CHECKED IN: the Android build must not
 * depend on a JVM task having been run, the same rule the launcher icons
 * follow. [GlyphVectorTest] fails when the checked-in file and this code
 * disagree, which is what stops the drawable drifting from the description.
 *
 * ## Only what is actually used
 *
 * Arcs and lines, and it THROWS on anything else rather than skipping it. The
 * bell glyph records what silent dropping costs: a writer that ignored a shape
 * it did not understand would have shipped a bell with no bell in it, and the
 * failure is invisible until it is on a wrist.
 */
object GlyphVector {

    /**
     * The drawable for one glyph, at the standard complication icon size.
     *
     * `?attr/colorOnSurface` is deliberately NOT used: a complication's
     * monochromatic image is tinted by the WATCH FACE, which is the whole
     * reason it is monochromatic. The path is white so the tint lands on
     * something.
     */
    fun toVectorDrawable(shapes: List<ComplicationGlyphs.Shape>, sizeDp: Int = 24): String {
        val paths = shapes.joinToString("\n") { path(it) }
        return """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by GlyphVector from ComplicationGlyphs. Do not hand-edit.
  Regenerate with: ./gradlew :workbench:glyphs
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${sizeDp}dp"
    android:height="${sizeDp}dp"
    android:viewportWidth="${fmt(ComplicationGlyphs.GRID)}"
    android:viewportHeight="${fmt(ComplicationGlyphs.GRID)}">
$paths
</vector>
"""
    }

    private fun path(shape: ComplicationGlyphs.Shape): String {
        val d = when (shape) {
            is ComplicationGlyphs.Shape.Arc -> arcData(shape)
            is ComplicationGlyphs.Shape.Line ->
                "M${fmt(shape.x1)},${fmt(shape.y1)} L${fmt(shape.x2)},${fmt(shape.y2)}"
            else -> throw IllegalArgumentException(
                "GlyphVector cannot draw ${shape::class.simpleName}. Add it rather than " +
                    "letting it be skipped -- a silently dropped shape ships as a missing icon."
            )
        }
        return """    <path
        android:pathData="$d"
        android:strokeColor="#FFFFFFFF"
        android:strokeWidth="${fmt(ComplicationGlyphs.STROKE_WIDTH)}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""
    }

    /**
     * An arc as an SVG elliptical-arc command.
     *
     * The conversion is the whole risk here, so it is spelled out.
     * [ComplicationGlyphs.Shape.Arc] is in AWT's convention: degrees
     * COUNTER-CLOCKWISE from 3 o'clock, on a y-down box. SVG measures its
     * sweep in the rendered, y-down frame, where counter-clockwise is
     * `sweep-flag = 0`. So the y term is negated to place the endpoints and
     * the sweep flag follows the SIGN of the extent, not its direction on a
     * whiteboard.
     */
    private fun arcData(a: ComplicationGlyphs.Shape.Arc): String {
        val rx = a.w / 2.0
        val ry = a.h / 2.0
        val cx = a.x + rx
        val cy = a.y + ry

        fun pointAt(deg: Double): Pair<Double, Double> {
            val r = Math.toRadians(deg)
            // Negated: AWT's angles rise where the screen's y falls.
            return (cx + rx * cos(r)) to (cy - ry * sin(r))
        }

        val (sx, sy) = pointAt(a.startDeg)
        val (ex, ey) = pointAt(a.startDeg + a.extentDeg)
        val largeArc = if (kotlin.math.abs(a.extentDeg) > 180.0) 1 else 0
        val sweep = if (a.extentDeg < 0.0) 1 else 0

        return "M${fmt(sx)},${fmt(sy)} " +
            "A${fmt(rx)},${fmt(ry)} 0 $largeArc,$sweep ${fmt(ex)},${fmt(ey)}"
    }

    /**
     * Three decimals, and no locale.
     *
     * `String.format` without a Locale writes "12,5" in half of Europe, and an
     * Android resource compiler does not accept that. The same trap
     * `WffEmitter` documents.
     */
    private fun fmt(v: Double): String =
        String.format(java.util.Locale.ROOT, "%.3f", v).trimEnd('0').trimEnd('.')
}
