package com.bfg.watchfaces.generator

/**
 * Emits the WFF definition for a set of params.
 *
 * Hard-won details, each of which cost a debugging session:
 *
 *  - Colours are #AARRGGBB. Eight digits, alpha FIRST. Six-digit colours are
 *    silently wrong, not rejected.
 *  - Ambient is per-element <Variant mode="AMBIENT" target="alpha" .../>,
 *    NOT a second Scene. Each element carries its interactive value as an
 *    attribute and its ambient value as a child.
 *  - DefaultProviderPolicy takes defaultSystemProvider / defaultSystemProviderType.
 *    NOT systemProvider / defaultType. Both compile, link, sign and install;
 *    the face then never appears in the carousel.
 *  - BoundingArc needs centerX/centerY. Rectangular slots want BoundingBox.
 *
 * WffSchemaTest validates the output of this class against Google's official
 * XSD on every build. Do not skip that test.
 */
object WffEmitter {

    private fun argb(rgb: String, alpha: Int = 255): String =
        "#%02x%s".format(alpha, rgb.removePrefix("#").lowercase())

    fun emit(p: DialParams, faceName: String = "Silver Sand"): String {
        // "Silver Sand" is the name of the DEFAULT FACE, not the app. The app is
        // BFG Watch Faces; Silver Sand is the warm-taupe botanical preset it
        // ships with. Do not conflate the two again.
        val l = p.layout
        val ink = argb(p.inkColor)
        val inkDim = argb(p.inkColor, 160)

        val slots = listOf(
            Triple(0, "STEP_COUNT", "@string/slot_steps"),
            Triple(1, "HEART_RATE", "@string/slot_heart"),
            Triple(2, "DAY_AND_DATE", "@string/slot_weather")
        ).joinToString("\n") { (id, provider, label) ->
            val w = (l.complicationSize * 4.7).toInt()
            val h = (l.complicationSize * 4.0).toInt()
            val x = DIAL_SIZE / 2 + (id - 1) * l.complicationSpread - w / 2
            val y = l.complicationY - (l.complicationSize * 1.2).toInt()
            """
    <ComplicationSlot slotId="$id" x="$x" y="$y" width="$w" height="$h"
                      displayName="$label"
                      supportedTypes="SHORT_TEXT MONOCHROMATIC_IMAGE EMPTY" alpha="255">
      <Variant mode="AMBIENT" target="alpha" value="0"/>
      <DefaultProviderPolicy defaultSystemProvider="$provider" defaultSystemProviderType="SHORT_TEXT"/>
      <BoundingBox x="0" y="0" width="$w" height="$h" outlinePadding="2.0"/>
      <Complication type="SHORT_TEXT">
        <PartText x="0" y="${(l.complicationSize * 1.4).toInt()}" width="$w" height="${(l.complicationSize * 1.8).toInt()}">
          <Text align="CENTER">
            <Font family="${l.fontFamily}" size="${(l.complicationSize * 0.92).toInt()}" color="$ink">
              <Template><![CDATA[%s]]><Parameter expression="[COMPLICATION.TEXT]"/></Template>
            </Font>
          </Text>
        </PartText>
        <PartImage x="${(w - l.complicationSize * 1.5).toInt() / 2}" y="0"
                   width="${(l.complicationSize * 1.5).toInt()}" height="${(l.complicationSize * 1.25).toInt()}">
          <Image resource="[COMPLICATION.MONOCHROMATIC_IMAGE]"/>
        </PartImage>
      </Complication>
    </ComplicationSlot>"""
        }

        // The emitted file is what ships, and since the workbench bakes it into
        // watchface-template it replaces what used to be a hand-annotated
        // reference. Carry that file's hard-won notes into the output so the
        // knowledge lives with the artefact instead of being overwritten by it.
        return """<?xml version="1.0" encoding="utf-8"?>
<!--
  $faceName - Watch Face Format definition.
  Generated by the BFG Watch Faces generator, v${p.generatorVersion}. Do not hand-edit:
  re-bake it instead, with ./gradlew :workbench:bake

  Canvas is 456x456: correct for Pixel Watch 4 and 5, both case sizes.
  Colours are AARRGGBB (8 digits, alpha FIRST). Six-digit values are silently
  wrong, not rejected.

  Ambient is handled by per-element Variant mode="AMBIENT", NOT by a second
  scene. Each element declares its interactive value as an attribute and its
  ambient value as a child.

  NOTE: the package in AndroidManifest.xml follows the Watch Face Push naming
  requirement, <app package>.watchfacepush.<face slug>. Push rejects anything
  else, and it lives in the binary manifest, so only pack can vary it at runtime.
-->
<WatchFace width="$DIAL_SIZE" height="$DIAL_SIZE">
  <Metadata key="CLOCK_TYPE" value="DIGITAL"/>
  <Metadata key="PREVIEW_TIME" value="10:10:00"/>

  <Scene backgroundColor="#ff000000">

    <PartImage x="0" y="0" width="$DIAL_SIZE" height="$DIAL_SIZE" alpha="255">
      <Variant mode="AMBIENT" target="alpha" value="0"/>
      <Image resource="dial_bg"/>
    </PartImage>

    <PartText x="0" y="${l.dateY - l.dateSize}" width="$DIAL_SIZE" height="${(l.dateSize * 1.9).toInt()}" alpha="255">
      <Variant mode="AMBIENT" target="alpha" value="140"/>
      <Text align="CENTER">
        <Font family="${l.fontFamily}" size="${l.dateSize}" weight="MEDIUM" color="$ink" letterSpacing="0.11">
          <Template><![CDATA[%s %s]]>
            <Parameter expression="[DAY_OF_WEEK_S]"/>
            <Parameter expression="[DAY]"/>
          </Template>
        </Font>
      </Text>
    </PartText>

    <DigitalClock x="0" y="${l.timeY - l.timeSize / 2}" width="$DIAL_SIZE" height="${(l.timeSize * 1.4).toInt()}">
      <TimeText format="hh:mm" hourFormat="SYNC_TO_DEVICE" align="CENTER"
                x="0" y="0" width="$DIAL_SIZE" height="${(l.timeSize * 1.4).toInt()}" alpha="255">
        <Variant mode="AMBIENT" target="alpha" value="0"/>
        <Font family="${l.fontFamily}" size="${l.timeSize}" weight="${l.fontWeight}" color="$ink"/>
      </TimeText>
      <TimeText format="hh:mm" hourFormat="SYNC_TO_DEVICE" align="CENTER"
                x="0" y="0" width="$DIAL_SIZE" height="${(l.timeSize * 1.4).toInt()}" alpha="0">
        <Variant mode="AMBIENT" target="alpha" value="255"/>
        <Font family="${l.fontFamily}" size="${l.timeSize}" weight="THIN" color="$inkDim"/>
      </TimeText>
    </DigitalClock>
$slots

    <PartText x="0" y="${l.batteryY - (l.complicationSize * 0.9).toInt()}" width="$DIAL_SIZE"
              height="${(l.complicationSize * 1.9).toInt()}" alpha="255">
      <Variant mode="AMBIENT" target="alpha" value="0"/>
      <Text align="CENTER">
        <Font family="${l.fontFamily}" size="${(l.complicationSize * 0.92).toInt()}" color="$ink">
          <Template><![CDATA[%d%%]]><Parameter expression="round([BATTERY_PERCENT])"/></Template>
        </Font>
      </Text>
    </PartText>

  </Scene>
</WatchFace>
"""
    }

    /**
     * Watch Face Push requires: <app package>.watchfacepush.<face name>
     * The API rejects anything else. Package name lives in the binary manifest,
     * so pack must generate it - it cannot be swapped into a prebuilt APK.
     */
    fun pushPackageName(appPackage: String, faceSlug: String): String {
        require(faceSlug.matches(Regex("^[a-z][a-z0-9_]*$"))) {
            "face slug must be lowercase alphanumeric/underscore, got '$faceSlug'"
        }
        return "$appPackage.watchfacepush.$faceSlug"
    }
}
